### PR TITLE
Few changes to get to compile

### PR DESCRIPTION
**Pull request by emstruong**
The real changes are in the `*.qmd` files and the `preamble.tex`.

### CODE REVIEW

**Review by friendly — COMMENTED** [review]
I'm not sure how to handle this PR since it also changes many files under `docs/`, which gives conflicts to be resolved.

I'd like to merge your changes to the `.qmd` files and the preamble, so I'll do this manually. There is probably some way to use `git cherry-pick`, but I'm not sure how this works.

**Comment by emstruong** [comment]
I think I was too hasty in requesting the pull request, it may be better for me to restart from your latest commit then to only make the small changes without compiling the project. 

Then, on a local duplicate branch I can compile the project to make sure that I made all the necessary changes. How about that?

**Comment by friendly** [comment]
I made your changes to the `.qmd` files and the `preamble.tex`, compiled to HTML and pushed.

Going forward, your suggestion above sounds reasonable.

**Comment by emstruong** [comment]
Well, looks like the master branch works, great!

**Pull request closed without merging**
